title: Matthew Robert Zender
description: Author of Real Family, Nick's Search for Purpose, and Muñeca.
url: "https://www.zenderbooks.com"
baseurl: "" # Empty for root, change if hosting in a subfolder locally
permalink: /:title.html
markdown: kramdown
plugins:
  - jekyll-seo-tag
